/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

public class PilhaTest {
    @Test
    public void testInserirUmElemento() {
        // montar o cenário
        Pilha pilha = new Pilha();

        // faz a ação
        pilha.empilhar(1);

        // executa o teste
        assertEquals(1, pilha.getTamanho());
    }

    @Test
    public void testInserirDoisElementos() {
        Pilha pilha = new Pilha();

        pilha.empilhar(1);
        pilha.empilhar(2);

        assertEquals(2, pilha.getTamanho());        
    }

    @Test
    public void testRemoverUmElemento() {
        Pilha pilha = new Pilha();
        pilha.empilhar(1);
        pilha.empilhar(2);
        pilha.empilhar(3);
        pilha.empilhar(4);

        int value = pilha.desempilhar();

        assertEquals(3, pilha.getTamanho());
        assertEquals(4, value);
    }

}
