/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.junit.Test;
import static org.junit.Assert.*;

public class FilaTest {
    @Test
    public void testInserirUmElemento() {
        // montar o cenário
        Fila fila = new Fila();

        // faz a ação
        fila.enfileirar(1);

        // executa o teste
        assertEquals(1, fila.getTamanho());
    }

    @Test
    public void testInserirDoisElementos() {
        Fila fila = new Fila();

        fila.enfileirar(1);
        fila.enfileirar(2);

        assertEquals(2, fila.getTamanho());
        assertEquals(2, fila.get(1));
    }

    @Test
    public void testRemoverUmElemento() {
        Fila fila = new Fila();
        fila.enfileirar(1);
        fila.enfileirar(2);
        fila.enfileirar(3);
        fila.enfileirar(4);

        fila.desenfileirar();

        assertEquals(3, fila.getTamanho());
        assertEquals(4, fila.get(2));
    }

}
